version: "3.7"
services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - backend

  backend:
    build: 
      context: ./backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app/
      - /var/run/docker.sock:/var/run/docker.sock  
    ports:
      - 8000:8000
    environment:
      - DATABASE_URI:${DATABASE_URI}
    depends_on: 
      - db
    networks:
      - frontend
      - backend
  frontend:
      build: 
        context: ./frontend
        target: base
      volumes:
        - ./frontend:/app/
      ports:
        - 8080:8080
      environment:
        - BACKEND_URL:${BACKEND_URL}
      networks:
        - frontend
        - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  postgres_data: